version: "3"
services:
  redis:
    container_name: redis
    image: redis:7.0.0-alpine
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data/redis
    restart: always